version: "3.8"

services:
  sonarqube:
    depends_on:
      - db
    image: mc1arke/sonarqube-with-community-branch-plugin:${SONARQUBE_VERSION}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        SONARQUBE_VERSION: ${SONARQUBE_VERSION}
        PLUGIN_VERSION: ${PLUGIN_VERSION}
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=${SONAR_JDBC_URL}
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
volumes:
  sonarqube_conf:
  sonarqube_data:
